# Uncomment this line to define a global platform for your project
 platform :ios, '9.0'

target '01-使用运行时进行图像的重绘' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for 01-使用运行时进行图像的重绘
pod 'ReactiveCocoa', '~> 4.0.4-alpha-4'

end
